@startuml
' Packages
package users {
  abstract class User {
    - id : int
    - name : String
    - email : String
    + {abstract} login()
    + {abstract} logout()
  }

  class Customer {
    -scooter:Scooter
    + makeReservation()
  }

  class MaintenanceOperator {
    + performMaintenance()
  }

  User <|-- Customer
  User <|-- MaintenanceOperator
}

package vehicles {
  class City {
    - name : String
    - scooters : Scooter[]

    +addScooter(scooter:Scooter):void
    +removeScooter(scooter:Scooter):void
  }

  class Scooter {
    - id : int
    - batteryLevel : int
  }

  City "1" *-- "0..*" Scooter
  Customer "1" --> "0..1" Scooter
}

package payments {
  class Payment {
    - amount : double
    - timestamp : Date
  }

  Customer "1" --> "*" Payment
}

package services {
  interface RentalService {
    + calculateCost(minutes : int) : double
  }

  class FixedRateRentalService {
    - ratePerMinute : double
    + calculateCost(minutes : int) : double
  }

  RentalService <|.. FixedRateRentalService
}


note right of payments
    Non espressamente richiesto ma
    potenzialmente utile
end note

@enduml
