@startuml

''nomi - singolari
'' CTRL+D = duplica riga
'' CTRL+SHIFT+arrows
:Arbitro: as arb
:Allenatore: as all
:FIGC: as f
:Squadra: as s
:Presidenza: as pres
:Giocatore: as gio

'' Confini del sistema
rectangle Calcio {
    usecase cal as "Creare Calendario"
    usecase save as "Salvare risultato"
    usecase part as "Creare partita"
    usecase desArb as "Designare arbitri"
    usecase showRes as "Visualizza risultato"
    usecase conv as "Convocare giocatore"
    usecase gGio as "Gestione giocatore"
    usecase aGIo as "acquistare giocatore"
    usecase vGio as "vendere giocatore"
    usecase printSched as "Stampare schedina"
    usecase changeAll as (cambiare allenatore)

}

f -- cal
f -- part
f -- desArb

all -- conv

arb --> save
pres -- changeAll
f -- showRes

pres -- gGio
gGio <.. aGIo : <<extend>>
gGio <.. vGio : <<extend>>
cal ..> part : <<include>>

note left of save
   RNF:
    - salvare risultato a fine evento
end note

@enduml